name: nokiagis
channels:
  - jmcmurray
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.1
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - attrs=21.4.0
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - bleach=5.0.0
  - bokeh=2.4.2
  - boost-cpp=1.74.0
  - branca=0.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.5.18.1
  - certifi=2022.5.18.1
  - cffi=1.15.0
  - cfitsio=3.470
  - charset-normalizer=2.0.12
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.4
  - contextily=1.2.0
  - cryptography=36.0.2
  - curl=7.68.0
  - cycler=0.11.0
  - debugpy=1.6.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - descartes=1.1.0
  - entrypoints=0.4
  - et_xmlfile=1.0.1
  - expat=2.4.8
  - fiona=1.8.9.post2
  - flask=2.0.3
  - flit-core=3.7.1
  - folium=0.12.1.post1
  - fonttools=4.32.0
  - freetype=2.10.4
  - freexl=1.0.6
  - gdal=2.4.2
  - geoalchemy2=0.6.3
  - geographiclib=1.52
  - geopandas=0.7.0
  - geopy=2.2.0
  - geos=3.7.2
  - geotiff=1.5.1
  - gettext=0.19.8.1
  - git=2.35.2
  - glib=2.70.2
  - glib-tools=2.70.2
  - greenlet=1.1.2
  - hdf4=4.2.15
  - hdf5=1.10.5
  - icu=64.2
  - idna=3.3
  - importlib-metadata=4.11.3
  - importlib_resources=5.6.0
  - intel-openmp=2022.0.0
  - ipykernel=6.13.0
  - ipython=7.32.0
  - ipython_genutils=0.2.0
  - itsdangerous=2.1.2
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.1.1
  - joblib=1.1.0
  - jpeg=9e
  - json=0.1.1
  - json5=0.9.5
  - jsonschema=4.4.0
  - jupyter_client=7.2.2
  - jupyter_core=4.9.2
  - jupyter_server=1.16.0
  - jupyterlab=3.3.3
  - jupyterlab_pygments=0.2.1
  - jupyterlab_server=2.12.0
  - kealib=1.4.13
  - kiwisolver=1.4.2
  - krb5=1.16.4
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.68.0
  - libdeflate=1.10
  - libffi=3.4.2
  - libgdal=2.4.2
  - libglib=2.70.2
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.6.2
  - libpng=1.6.37
  - libpq=11.5
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.10.0
  - libtiff=4.3.0
  - libxml2=2.9.13
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - m2w64-expat=2.1.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gettext=0.19.7
  - m2w64-gmp=6.1.0
  - m2w64-libiconv=1.14
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-xz=5.2.2
  - markupsafe=2.1.1
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.3
  - mercantile=1.2.1
  - mistune=0.8.4
  - mkl=2022.0.0
  - msys2-conda-epoch=20160418
  - munch=2.5.0
  - munkres=1.1.4
  - nbclassic=0.3.7
  - nbclient=0.6.0
  - nbconvert=6.5.0
  - nbconvert-core=6.5.0
  - nbconvert-pandoc=6.5.0
  - nbformat=5.3.0
  - nest-asyncio=1.5.5
  - notebook=6.4.10
  - notebook-shim=0.1.0
  - numpy=1.21.6
  - olefile=0.46
  - openjpeg=2.3.1
  - openpyxl=3.0.9
  - openssl=1.1.1o
  - packaging=21.3
  - pandas=1.3.5
  - pandoc=2.18
  - pandocfilters=1.5.0
  - parso=0.8.3
  - patsy=0.5.2
  - pcre=8.45
  - pickleshare=0.7.5
  - pillow=8.1.2
  - pip=22.0.4
  - poppler=0.67.0
  - poppler-data=0.4.11
  - postgresql=11.5
  - proj4=6.1.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.29
  - psutil=5.9.0
  - psycopg2=2.8.4
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.8
  - pyproj=2.2.0
  - pyqt=5.9.2
  - pyrsistent=0.18.1
  - pysocks=1.7.1
  - python=3.7.12
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.3
  - python_abi=3.7
  - pytz=2022.1
  - pywin32=303
  - pywinpty=2.0.5
  - pyyaml=6.0
  - pyzmq=22.3.0
  - qt=5.9.7
  - qutil=3.2.1
  - rasterio=1.0.28
  - requests=2.27.1
  - rtree=1.0.0
  - scipy=1.7.3
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - send2trash=1.8.0
  - setuptools=59.8.0
  - shapely=1.6.4
  - sip=4.19.8
  - six=1.16.0
  - sniffio=1.2.0
  - snuggs=1.4.7
  - soupsieve=2.3.1
  - sqlalchemy=1.4.35
  - sqlite=3.38.2
  - statsmodels=0.13.2
  - tabulate=0.8.9
  - tbb=2021.5.0
  - terminado=0.13.3
  - tinycss2=1.1.1
  - tk=8.6.12
  - tornado=6.1
  - traitlets=5.1.1
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - ucrt=10.0.20348.0
  - unicodedata2=14.0.0
  - urllib3=1.26.9
  - vc=14.2
  - vs2015_runtime=14.29.30037
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.3.2
  - werkzeug=2.1.1
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xerces-c=3.2.2
  - xyzservices=2022.3.0
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.11
  - zstd=1.5.2
